//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input Actions/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""b8592738-b24e-4fbf-89e8-85531c118bc3"",
            ""actions"": [
                {
                    ""name"": ""MovementForward"",
                    ""type"": ""Value"",
                    ""id"": ""32551604-e961-4d92-9580-cf441b031096"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MovementRotation"",
                    ""type"": ""Button"",
                    ""id"": ""ab08b589-0f05-4169-8f24-d626a576411a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootCannon"",
                    ""type"": ""Button"",
                    ""id"": ""57c926e1-65a7-4371-beb4-7a54d7ade62d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootCannonSpecial"",
                    ""type"": ""Button"",
                    ""id"": ""12a358ff-4894-4c2e-a9d7-c049e791fc05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0d06b84e-4b29-4bc0-a52a-054605fd0d37"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""id"": ""e4490771-249a-4da9-a969-6956803d34fd"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementRotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c3bd98f0-c5b5-4b62-a3fb-8003d2511632"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""bf4665bf-bcc9-42d0-b1e2-af14efddefab"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d2b75ca6-df2a-4f64-8185-d09ab286868b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootCannon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""709c8735-c968-4f4e-a2c2-bd1a64e2bba1"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootCannonSpecial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_MovementForward = m_Player.FindAction("MovementForward", throwIfNotFound: true);
        m_Player_MovementRotation = m_Player.FindAction("MovementRotation", throwIfNotFound: true);
        m_Player_ShootCannon = m_Player.FindAction("ShootCannon", throwIfNotFound: true);
        m_Player_ShootCannonSpecial = m_Player.FindAction("ShootCannonSpecial", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_MovementForward;
    private readonly InputAction m_Player_MovementRotation;
    private readonly InputAction m_Player_ShootCannon;
    private readonly InputAction m_Player_ShootCannonSpecial;
    public struct PlayerActions
    {
        private @InputActions m_Wrapper;
        public PlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovementForward => m_Wrapper.m_Player_MovementForward;
        public InputAction @MovementRotation => m_Wrapper.m_Player_MovementRotation;
        public InputAction @ShootCannon => m_Wrapper.m_Player_ShootCannon;
        public InputAction @ShootCannonSpecial => m_Wrapper.m_Player_ShootCannonSpecial;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @MovementForward.started += instance.OnMovementForward;
            @MovementForward.performed += instance.OnMovementForward;
            @MovementForward.canceled += instance.OnMovementForward;
            @MovementRotation.started += instance.OnMovementRotation;
            @MovementRotation.performed += instance.OnMovementRotation;
            @MovementRotation.canceled += instance.OnMovementRotation;
            @ShootCannon.started += instance.OnShootCannon;
            @ShootCannon.performed += instance.OnShootCannon;
            @ShootCannon.canceled += instance.OnShootCannon;
            @ShootCannonSpecial.started += instance.OnShootCannonSpecial;
            @ShootCannonSpecial.performed += instance.OnShootCannonSpecial;
            @ShootCannonSpecial.canceled += instance.OnShootCannonSpecial;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @MovementForward.started -= instance.OnMovementForward;
            @MovementForward.performed -= instance.OnMovementForward;
            @MovementForward.canceled -= instance.OnMovementForward;
            @MovementRotation.started -= instance.OnMovementRotation;
            @MovementRotation.performed -= instance.OnMovementRotation;
            @MovementRotation.canceled -= instance.OnMovementRotation;
            @ShootCannon.started -= instance.OnShootCannon;
            @ShootCannon.performed -= instance.OnShootCannon;
            @ShootCannon.canceled -= instance.OnShootCannon;
            @ShootCannonSpecial.started -= instance.OnShootCannonSpecial;
            @ShootCannonSpecial.performed -= instance.OnShootCannonSpecial;
            @ShootCannonSpecial.canceled -= instance.OnShootCannonSpecial;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMovementForward(InputAction.CallbackContext context);
        void OnMovementRotation(InputAction.CallbackContext context);
        void OnShootCannon(InputAction.CallbackContext context);
        void OnShootCannonSpecial(InputAction.CallbackContext context);
    }
}
